[package]
name = "stargazer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
serde = "1.0.188"

[[bin]]
name = "stargazer"
path = "src/main.rs"
