[package]
name = "stargazer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stargazer"
path = "src/main.rs"

[dependencies]
futures = "0.3.29"
iced = {version = "0.10.0", features = ["image", "tokio"] }
reqwest = "0.11.22"
secstr = "0.5.1"
serde = "1.0.190"

