[package]
name = "stargazer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stargazer"
path = "src/main.rs"

[dependencies]
iced = {version = "0.10.0", features = ["image"] }
reqwest = "0.11.22"
serde = "1.0.190"

