[package]
name = "stargazer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stargazer-gui"
path = "src/gui/main.rs"


[[bin]]
name = "stargazer-daemon"
path = "src/daemon/main.rs"

[dependencies]
futures = "0.3.29"
iced = {version = "0.10.0", features = ["image", "tokio"] }
reqwest = {version = "0.11.22", features = ["json"]}
secstr = "0.5.1"
serde = "1.0.190"
serde_json = "1.0.108"

