appenders:
  service_logger:
    kind: file
    path: "C:\Users\HenryBaldwin\Dev\stargazer\target\debug\log\service.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
root:
  level: trace
  appenders:
    - service_logger